# Generated by Django 4.2.4 on 2023-09-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('S', 'Simple'), ('V', 'VIP'), ('A', 'Admin')], max_length=2, verbose_name='Membership'),
        ),
    ]
