# Generated by Django 4.2.4 on 2023-09-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_membership_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('S', 'Simple'), ('V', 'VIP'), ('A', 'Admin')], default='Simple', max_length=20, verbose_name='Membership'),
        ),
    ]
